---
- name: play level variables
  hosts: web

  vars_files:
    - course.yaml
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"
