---
- name: play level variables
  hosts: web

  vars:
    COURSE: "DevOps With AWS"
    DURATION: "140HRS"
    TRAINER: "Sivakumar Reddy"

  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"
